### PR TITLE
Chore/works and about section

### PR DESCRIPTION
**Pull request by Reconfort**
## What does this PR do?
1. Creating Works and About section

## How can this changes be manually tested
1. Clone this project
3. Navigate into cloned Project
4. run `npm install`
5. open index.html in browser

Previous PR link: https://github.com/Reconfort/Mobile-Portifolio/pull/1

### CODE REVIEW

**Comment by topeogunleye** [comment]
@Fernando426, great job on this PR. To make the review process easier, could you please include the link to the previous PR where you got some suggestions for improvement? You can add the link to your PR description like this:

Previous PR link: https://github.com/Reconfort/Mobile-Portifolio/pull/1

**Comment by Reconfort** [comment]
> @Fernando426, great job on this PR. To make the review process easier, could you please include the link to the previous PR where you got some suggestions for improvement? You can add the link to your PR description like this:
> 
> `Previous PR link: https://github.com/Reconfort/Mobile-Portifolio/pull/1 `

**Comment by Reconfort** [comment]
> @Fernando426, great job on this PR. To make the review process easier, could you please include the link to the previous PR where you got some suggestions for improvement? You can add the link to your PR description like this:
> 
> `Previous PR link: https://github.com/Reconfort/Mobile-Portifolio/pull/1 `

@topeogunleye I added link in description

**Comment by topeogunleye** [comment]
> 

@Reconfort, you have one more change to make. you styling for hover button interaction is wrong, and you need to add styling for button pressed interaction:

the button on the pressed state has the `background: #2230D2;` and on hover has the `background: #6070FF;`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

**Comment by Reconfort** [comment]
> @Reconfort, you have one more change to make. you styling for hover button interaction is wrong, and you need to add styling for button pressed interaction. Please make the change so that I can approve
> 
> the button on the pressed state has the `background: #2230D2;` and on hover has the `background: #6070FF;`
> 
> ### EXAMPLE:
> **for pressed state**
> 
> ```
> button:active {
>    background-color: #2230D2;
> }
> ```
> 
> **for hover state**
> 
> ```
> button:hover {
>     background-color: #6070FF;
> }
> ```

I have updated my code check/

**Review by topeogunleye — APPROVED** [review]
### Hi @Reconfort, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
congratulations
>
## To highlight :champagne: 
- Used a hx tag for headers :heavy_check_mark: 
- Used a ul tag to group a list of icons, and li per icon :heavy_check_mark: 
- Added button interactions :heavy_check_mark:
- Fixed icons not displaying. :heavy_check_mark:
- Used p tag for paragraphs :heavy_check_mark:
 
## [Optional] suggestions:
- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
image

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
